/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'avasharm' at '7/29/16 12:27 PM' with Gradle 2.14.1
 *
 * @author avasharm, @date 7/29/16 12:27 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
